In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests

file = "project-1-/Net_generation_for_all_sectors.csv"

# Read our Kickstarter data into pandas
df = pd.read_csv(file)
df

,Net generation for all sectors,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241
0,https://www.eia.gov/electricity/data/browser/#...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sat Jan 30 2021 12:20:00 GMT-0700 (Mountain St...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Source: U.S. Energy Information Administration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,description,units,source key,Jan-01,Feb-01,Mar-01,Apr-01,May-01,Jun-01,Jul-01,...,Feb-20,Mar-20,Apr-20,May-20,Jun-20,Jul-20,Aug-20,Sep-20,Oct-20,Nov-20
4,Net generation for all sectors,thousand megawatthours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii : hydro-electric pumped storage,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
1303,Hawaii : other,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,25,30,23,27,21,30,28,21,19,31
1304,Hawaii : all solar,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,119,136,153,167,164,168,167,155,140,123
1305,Hawaii : small-scale solar photovoltaic,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,87,99,107,114,113,116,115,106,99,87
1306,Hawaii : all utility-scale solar,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,33,37,46,53,51,52,52,49,41,36

In [3]:
energy_date_df=df.drop([0, 1, 2, 4])

In [5]:
energy_date_df[['Net generation for all sectors', 'Energy Source']] = energy_date_df['Net generation for all sectors'].str.split(':', expand=True)
energy_date_df

,Net generation for all sectors,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Energy Source
3,description,units,source key,Jan-01,Feb-01,Mar-01,Apr-01,May-01,Jun-01,Jul-01,...,Mar-20,Apr-20,May-20,Jun-20,Jul-20,Aug-20,Sep-20,Oct-20,Nov-20,None
5,United States,NaN,ELEC.GEN..M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,United States,thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,357614,...,306887,275763,304167,352967,414610,399812,334167,314401,301776,all fuels (utility-scale)
7,United States,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,179060,...,50643,40593,46529,65274,89845,91165,68396,59840,61291,coal
8,United States,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,10050,...,715,636,707,865,963,926,795,911,761,petroleum liquids
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,hydro-electric pumped storage
1303,Hawaii,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,30,23,27,21,30,28,21,19,31,other
1304,Hawaii,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,136,153,167,164,168,167,155,140,123,all solar
1305,Hawaii,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,99,107,114,113,116,115,106,99,87,small-scale solar photovoltaic
1306,Hawaii,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,37,46,53,51,52,52,49,41,36,all utility-scale solar

In [ ]:
# set row 3 as header, can make row 3 a list and make that a column header somehow
energy_date_df[['']]