In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
file = "../Net_generation_for_all_sectors_fixed_dates.csv"
# file = "../Net_generation_for_all_sectors (1).csv"

# Read our Kickstarter data into pandas
df = pd.read_csv(file)
df

,Net generation for all sectors,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241
0,https://www.eia.gov/electricity/data/browser/#...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sat Jan 30 2021 12:20:00 GMT-0700 (Mountain St...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Source: U.S. Energy Information Administration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov
4,Net generation for all sectors,thousand megawatthours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii : hydro-electric pumped storage,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
1303,Hawaii : other,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,25,30,23,27,21,30,28,21,19,31
1304,Hawaii : all solar,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,119,136,153,167,164,168,167,155,140,123
1305,Hawaii : small-scale solar photovoltaic,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,87,99,107,114,113,116,115,106,99,87
1306,Hawaii : all utility-scale solar,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,33,37,46,53,51,52,52,49,41,36

In [4]:
energy_df=df.drop([0, 1, 2, 4])

In [5]:
energy_df[['Net generation for all sectors', 'Energy Source']] = energy_df['Net generation for all sectors'].str.split(':', expand=True)
energy_df

,Net generation for all sectors,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Energy Source
3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov,None
5,United States,NaN,ELEC.GEN..M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,United States,thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,357614,...,306887,275763,304167,352967,414610,399812,334167,314401,301776,all fuels (utility-scale)
7,United States,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,179060,...,50643,40593,46529,65274,89845,91165,68396,59840,61291,coal
8,United States,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,10050,...,715,636,707,865,963,926,795,911,761,petroleum liquids
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,hydro-electric pumped storage
1303,Hawaii,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,30,23,27,21,30,28,21,19,31,other
1304,Hawaii,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,136,153,167,164,168,167,155,140,123,all solar
1305,Hawaii,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,99,107,114,113,116,115,106,99,87,small-scale solar photovoltaic
1306,Hawaii,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,37,46,53,51,52,52,49,41,36,all utility-scale solar

In [6]:
# set row 3 as header, can make row 3 a list and make that a column header somehow
# energy_date_df[['']]
header_row= 0
energy_df.columns= energy_df.iloc[header_row]
energy_df

3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov,NaN
3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov,None
5,United States,NaN,ELEC.GEN..M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,United States,thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,357614,...,306887,275763,304167,352967,414610,399812,334167,314401,301776,all fuels (utility-scale)
7,United States,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,179060,...,50643,40593,46529,65274,89845,91165,68396,59840,61291,coal
8,United States,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,10050,...,715,636,707,865,963,926,795,911,761,petroleum liquids
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,hydro-electric pumped storage
1303,Hawaii,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,30,23,27,21,30,28,21,19,31,other
1304,Hawaii,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,136,153,167,164,168,167,155,140,123,all solar
1305,Hawaii,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,99,107,114,113,116,115,106,99,87,small-scale solar photovoltaic
1306,Hawaii,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,37,46,53,51,52,52,49,41,36,all utility-scale solar

In [7]:
# Drop extra and empty rows
energy_df= energy_df.drop([3, 5])
energy_df

3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov,NaN
6,United States,thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,357614,...,306887,275763,304167,352967,414610,399812,334167,314401,301776,all fuels (utility-scale)
7,United States,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,179060,...,50643,40593,46529,65274,89845,91165,68396,59840,61291,coal
8,United States,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,10050,...,715,636,707,865,963,926,795,911,761,petroleum liquids
9,United States,thousand megawatthours,ELEC.GEN.PC-US-99.M,812,716,752,627,749,825,992,...,684,591,587,808,907,809,457,322,643,petroleum coke
10,United States,thousand megawatthours,ELEC.GEN.NG-US-99.M,42389,37967,44364,45843,50934,57603,73030,...,123654,107929,115855,143180,185433,174130,141407,131644,107821,natural gas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,hydro-electric pumped storage
1303,Hawaii,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,30,23,27,21,30,28,21,19,31,other
1304,Hawaii,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,136,153,167,164,168,167,155,140,123,all solar
1305,Hawaii,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,99,107,114,113,116,115,106,99,87,small-scale solar photovoltaic
1306,Hawaii,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,37,46,53,51,52,52,49,41,36,all utility-scale solar

In [8]:
cols = list(energy_df.columns.values)
cols

['description',
 'units',
 'source key',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 '1-Dec',
 '1-Jan',
 '1-Feb',
 '1-Mar',
 '1-Apr',
 '1-May',
 '1-Jun',
 '1-Jul',
 '1-Aug',
 '1-Sep',
 '1-Oct',
 '1-Nov',
 None]

In [9]:
# Rename empty column heading as "Energy_Source"
energy_df.rename(columns = {None: "Energy_Source"}, inplace= True)
energy_df

3,description,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,...,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov,Energy_Source
6,United States,thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,357614,...,306887,275763,304167,352967,414610,399812,334167,314401,301776,all fuels (utility-scale)
7,United States,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,179060,...,50643,40593,46529,65274,89845,91165,68396,59840,61291,coal
8,United States,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,10050,...,715,636,707,865,963,926,795,911,761,petroleum liquids
9,United States,thousand megawatthours,ELEC.GEN.PC-US-99.M,812,716,752,627,749,825,992,...,684,591,587,808,907,809,457,322,643,petroleum coke
10,United States,thousand megawatthours,ELEC.GEN.NG-US-99.M,42389,37967,44364,45843,50934,57603,73030,...,123654,107929,115855,143180,185433,174130,141407,131644,107821,natural gas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,hydro-electric pumped storage
1303,Hawaii,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,18,...,30,23,27,21,30,28,21,19,31,other
1304,Hawaii,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,--,...,136,153,167,164,168,167,155,140,123,all solar
1305,Hawaii,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,--,...,99,107,114,113,116,115,106,99,87,small-scale solar photovoltaic
1306,Hawaii,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,--,...,37,46,53,51,52,52,49,41,36,all utility-scale solar

In [10]:
# Move the Energy_Source column from the end of the dataframe to the far left side
mid = energy_df['Energy_Source']
energy_df.drop(labels=['Energy_Source'], axis = 1, inplace = True)
energy_df.insert(1, 'Energy_Source', mid)
energy_df

3,description,Energy_Source,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,...,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov
6,United States,all fuels (utility-scale),thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,...,317853,306887,275763,304167,352967,414610,399812,334167,314401,301776
7,United States,coal,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,...,56101,50643,40593,46529,65274,89845,91165,68396,59840,61291
8,United States,petroleum liquids,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,...,766,715,636,707,865,963,926,795,911,761
9,United States,petroleum coke,thousand megawatthours,ELEC.GEN.PC-US-99.M,812,716,752,627,749,825,...,500,684,591,587,808,907,809,457,322,643
10,United States,natural gas,thousand megawatthours,ELEC.GEN.NG-US-99.M,42389,37967,44364,45843,50934,57603,...,125554,123654,107929,115855,143180,185433,174130,141407,131644,107821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,hydro-electric pumped storage,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
1303,Hawaii,other,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,...,25,30,23,27,21,30,28,21,19,31
1304,Hawaii,all solar,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,...,119,136,153,167,164,168,167,155,140,123
1305,Hawaii,small-scale solar photovoltaic,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,...,87,99,107,114,113,116,115,106,99,87
1306,Hawaii,all utility-scale solar,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,...,33,37,46,53,51,52,52,49,41,36

In [11]:
energy_df.Energy_Source.unique()

array([' all fuels (utility-scale)', ' coal', ' petroleum liquids',
       ' petroleum coke', ' natural gas', ' other gases', ' nuclear',
       ' conventional hydroelectric', ' other renewables', ' wind',
       ' all utility-scale solar', ' geothermal', ' biomass',
       ' wood and wood-derived fuels', ' other biomass',
       ' hydro-electric pumped storage', ' other', ' all solar',
       ' small-scale solar photovoltaic', None], dtype=object)

In [12]:
# Group energy sources by renewables and nonrenewables 
renewables = ["conventional hydroelectric", "other renewables", "wind", "all utility-scale solar", "biomass", "wood and wood-derived fuels", "other biomass", "hydro-electric pumped storage", "all solar", "small-scale solar photovoltaic"]
nonrenewables = ["coal", "petroleum liquids", "petroleum coke", "natural gas", "other gases"]

In [13]:
# Rename description column to location 
energy_df.rename(columns = {"description": "Location"}, inplace= True)
energy_df

3,Location,Energy_Source,units,source key,1-Jan,1-Feb,1-Mar,1-Apr,1-May,1-Jun,...,1-Feb,1-Mar,1-Apr,1-May,1-Jun,1-Jul,1-Aug,1-Sep,1-Oct,1-Nov
6,United States,all fuels (utility-scale),thousand megawatthours,ELEC.GEN.ALL-US-99.M,332493,282940,300707,278079,300492,327694,...,317853,306887,275763,304167,352967,414610,399812,334167,314401,301776
7,United States,coal,thousand megawatthours,ELEC.GEN.COW-US-99.M,177287,149735,155269,140671,151593,162616,...,56101,50643,40593,46529,65274,89845,91165,68396,59840,61291
8,United States,petroleum liquids,thousand megawatthours,ELEC.GEN.PEL-US-99.M,17300,9626,10981,10237,9641,10997,...,766,715,636,707,865,963,926,795,911,761
9,United States,petroleum coke,thousand megawatthours,ELEC.GEN.PC-US-99.M,812,716,752,627,749,825,...,500,684,591,587,808,907,809,457,322,643
10,United States,natural gas,thousand megawatthours,ELEC.GEN.NG-US-99.M,42389,37967,44364,45843,50934,57603,...,125554,123654,107929,115855,143180,185433,174130,141407,131644,107821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,Hawaii,hydro-electric pumped storage,thousand megawatthours,ELEC.GEN.HPS-HI-99.M,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
1303,Hawaii,other,thousand megawatthours,ELEC.GEN.OTH-HI-99.M,12,12,5,15,17,19,...,25,30,23,27,21,30,28,21,19,31
1304,Hawaii,all solar,thousand megawatthours,ELEC.GEN.TSN-HI-99.M,--,--,--,--,--,--,...,119,136,153,167,164,168,167,155,140,123
1305,Hawaii,small-scale solar photovoltaic,thousand megawatthours,ELEC.GEN.DPV-HI-99.M,--,--,--,--,--,--,...,87,99,107,114,113,116,115,106,99,87
1306,Hawaii,all utility-scale solar,thousand megawatthours,ELEC.GEN.SUN-HI-99.M,--,--,--,--,--,--,...,33,37,46,53,51,52,52,49,41,36

In [14]:
energy_df=energy_df.dropna()
energy_df.count()

3
Location         1178
Energy_Source    1178
units            1178
source key       1178
1-Jan            1178
                 ...
1-Jul            1178
1-Aug            1178
1-Sep            1178
1-Oct            1178
1-Nov            1178
Length: 243, dtype: int64

In [15]:
state_energy=energy_df.groupby("Location")
state_energy.Location.unique()

Location
Alabama                           [Alabama ]
Alaska                             [Alaska ]
Arizona                           [Arizona ]
Arkansas                         [Arkansas ]
California                     [California ]
                               ...
West North Central     [West North Central ]
West South Central     [West South Central ]
West Virginia               [West Virginia ]
Wisconsin                       [Wisconsin ]
Wyoming                           [Wyoming ]
Name: Location, Length: 62, dtype: object

In [16]:
energy_df.count()

3
Location         1178
Energy_Source    1178
units            1178
source key       1178
1-Jan            1178
                 ...
1-Jul            1178
1-Aug            1178
1-Sep            1178
1-Oct            1178
1-Nov            1178
Length: 243, dtype: int64

In [17]:

us_energy= state_energy(state_energy(["Location"]=="United States"))


#us_energy=state_energy[(state_energy["Location"]=="United States")]
# state_energy.head()

TypeError: 'DataFrameGroupBy' object is not callable

In [ ]:
#energy_sources = energy_df['Energy_Source'].tolist()
#print(energy_sources)

In [ ]:
#def movecol(energy_date_df, cols_to_move=["Energy_Source"], ref_col = "description", place = "After"):
    #cols = energy_date_df.columns.tolist()


#energy_data= energy_date_df.movecol(energy_date_df,
#                     cols_to_move = ['Energy_Source'],
#                     ref_col = 'description',
#                     place='After')
#energy_data

In [ ]:
#energy_date_df=energy_date_df.reset_index(drop=True)
# energy_date_df=df.drop([0, 1, 2, 4])
# energy_date_df.columns= energy_date_df.iloc[header_row]
#energy=energy_date_df.replace('NaN', 'Energy_Source')
#energy

#energy_df=energy_date_df.insert('description', 'units', 'source key', 'None')
# energy_df
#energy_data = energy_date_df['None']
#energy_data
#energy_data=energy_date_df.rename(columns={np.nan: "Fuel Source"}, inplace = True)
#energy_data
#energy_data= energy_date_df.columns.fillna("Fuel Source")
#energy_data
#energy_df.columns.get_loc("Energy_Source")